### ISSUE TITLE
Question: Can this Tag run without Snowplow?

### ISSUE THREAD

**Issue by jonathanarbely** [snowplow/snowplow-gtm-server-side-braze-tag#2]
In the [README](https://github.com/snowplow/snowplow-gtm-server-side-braze-tag/blob/main/README.md?plain=1#L17) you say that this Tag is "best used" in conjunction with Snowplow. But can it be used Standalone in a server-side GTM environment? That's what your text would suggest.

Any insights on that are greatly appreciated. 🙏🏼

**Comment by adatzer** [comment]
Hello @jonathanarbely ! You are exactly right: the [Snowplow GTM-SS Braze Tag](https://docs.snowplowanalytics.com/docs/forwarding-events-to-destinations/forwarding-events/google-tag-manager-server-side/braze-tag-for-gtm-ss/) can also be used independently, i.e. you can use it to forward any gtm server-side events to Braze. 

The "best used" refers to the fact that the tag configuration includes sections (`Snowplow Event Mapping Options`) that specifically target Snowplow events and thus work best along with the [Snowplow Client](https://github.com/snowplow/snowplow-gtm-server-side-client/). The rest of the configuration options should still work best with any gtm-ss client, so please let us know if there is anything that doesn't work as expected.

![braze-tag-config-detail](https://user-images.githubusercontent.com/35838196/173032183-7cfa754a-b115-4268-b637-15bf066f574a.png)

Also, feel free to join the Snowplow community on [Discourse](https://discourse.snowplowanalytics.com/) and open a discussion anytime!

**Comment by jonathanarbely** [comment]
Thank you very much for your quick response! I do appreciate that.

May I ask if it would be possible to make the `Braze external_id` field optional, so that the Tag could be used to [alias](https://www.braze.com/docs/api/endpoints/user_data/post_user_alias/) new, unknown users?

**Comment by adatzer** [comment]
@jonathanarbely, apologies for missing this out.
Just opened https://github.com/snowplow/snowplow-gtm-server-side-braze-tag/issues/3 specifically about supporting user aliasing.
Let's close this issue and track this separately there!
